# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AUC_calc <- function(X, W) {
    .Call('_tdROC_AUC_calc', PACKAGE = 'tdROC', X, W)
}

AUC_calc2 <- function(X, W1, W2) {
    .Call('_tdROC_AUC_calc2', PACKAGE = 'tdROC', X, W1, W2)
}

